name: POI_CI_CD

on:
  workflow_dispatch:
  push:
    paths:
      - 'apis/poi/**'
    branches: [ dev ]
#  pull_request:
#    branches: [ dev ]


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['3.1.x']

    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: apis/poi/
    - name: Build
      run: dotnet build apis/poi/poi.sln --no-restore 
    - name: Test
      run: dotnet test apis/poi/tests/UnitTests/UnitTests.csproj --no-build --verbosity normal
